const express = require('express');
const app = express();

// Array of English words
const words = [
      'knowledge', 'chat', 'science', 'cat', 'rat',
      'dog', 'elephant', 'lion', 'tiger', 'giraffe',
      'zebra', 'computer', 'internet', 'python', 'language',
      'programming', 'code', 'algorithm', 'database', 'server',
      'client', 'network', 'router', 'firewall', 'security',
      'encryption', 'password', 'authentication', 'authorization', 'token',
      'session', 'cookie', 'cache', 'browser', 'website',
      'webpage', 'html', 'css', 'javascript', 'react',
      'angular', 'vue', 'framework', 'library', 'api',
      'json', 'xml', 'http', 'https', 'ftp',
      'smtp', 'tcp', 'ip', 'dns', 'url',
      'uri', 'ssl', 'tls', 'rsa', 'aes',
      'des', 'md5', 'sha', 'jwt', 'oauth',
      'openid', 'linux', 'unix', 'windows', 'macos',
      'ios', 'android', 'mobile', 'desktop', 'laptop',
      'server', 'cloud', 'virtualization', 'containerization', 'docker',
      'kubernetes', 'devops', 'ci/cd', 'git', 'github',
      'gitlab', 'bitbucket', 'repository', 'branch', 'merge',
      'pull_request', 'issue', 'bug', 'feature', 'enhancement',
      'release', 'version', 'dependency', 'package', 'module',
      'library', 'plugin', 'extension', 'middleware', 'backend',
      'frontend', 'full-stack', 'responsive', 'adaptive', 'mobile-first',
      'seo', 'sem', 'analytics', 'tracking', 'conversion',
      'bounce_rate', 'ctr', 'roi', 'cms', 'wordpress',
      'joomla', 'drupal', 'magento', 'shopify', 'woocommerce',
      'prestashop', 'opencart', 'bigcommerce', 'squarespace', 'wix',
      'weebly', 'ghost', 'blogger', 'tumblr', 'medium',
      'deviantart', 'behance', 'dribbble', 'pinterest', 'instagram',
      'facebook', 'twitter', 'linkedin', 'youtube', 'twitch',
      'tiktok', 'reddit', 'snapchat', 'whatsapp', 'messenger',
      'skype', 'zoom', 'slack', 'discord', 'telegram',
      'signal', 'google', 'amazon', 'microsoft', 'apple',
      'stripe', 'paypal', 'square', 'authorize_net', 'adyen',
      'worldpay', 'braintree', '2checkout', 'bitpay', 'coinbase',
      'binance', 'kraken', 'bitfinex', 'huobi', 'okex',
      'bittrex', 'gemini', 'poloniex', 'coincheck', 'bitstamp',
      'liquid', 'cex.io', 'localbitcoins', 'paxful', 'kucoin',
      'bitflyer', 'gate.io', 'btc-e', 'hitbtc', 'btc_markets',
      'coinfloor', 'coinbase_pro', 'bitbay', 'bitso', 'btc-alpha',
      'bitbank', 'luno', 'uniswap', 'sushiswap', 'pancakeswap',
      'balancer', 'aave', 'compound', 'maker', 'synthetix',
      'yearn.finance', 'chainlink', 'renvm', 'filecoin', 'tezos',
      'algorand', 'stellar', 'tron', 'eos', 'neo',
      'iota', 'vechain', 'dash', 'zcash', 'monero',
      'ethereum_classic', 'dogecoin', 'nem', 'bitcoin_cash', 'litecoin',
      'cardano', 'polkadot', 'ripple', 'ethereum', 'bitcoin',
      'cryptocurrency', 'blockchain', 'decentralized', 'smart_contract', 'tokenization',
      'nft', 'dao', 'defi', 'metaverse', 'digital_asset',
      'mining', 'hashrate', 'proof_of_work', 'proof_of_stake', 'consensus',
      'wallet', 'exchange', 'broker', 'investment', 'trading',
      'speculation', 'bubble', 'bull_market', 'bear_market', 'correction',
      'crash', 'volatility', 'liquidity', 'market_cap', 'market_order',
      'limit_order', 'stop_order', 'margin', 'leverage', 'long_position',
      'short_position', 'liquidation', 'rekt',

   'emperor',
   'king',
   'queen',
   'prince',
   'princess',
   'duke',
   'duchess',
   'earl',
   'count',
   'countess',
   'baron',
   'scepter',
   'throne',
   'regent',
   'monarch',
   'sovereign',
   'nobility',
   'realm',
   'crown',
   'palace',
   'castle',
   'lord',
   'lady',
   'regalia',
   'royalty',
   'heir',
   'dynasty',
   'court',
   'bishop',
   'archbishop',
   'pope',
   'cardinal',
   'clergy',
   'mitre',
   'abbey',
   'monastery',
   'nun',
   'friar',
   'priest',
   'vicar',
   'pastor',
   'minister',
   'prelate',
   'chaplain',
   'diocese',
   'parish',
   'convent',
   'vestments',
   'cassock',
   'holy',
   'crusade',
   'pilgrim',
   'devotion',
   'worship',
   'sanctuary',
   'sermon',
   'blessing',
   'prayer',
   'psalm',
   'doctrine',
   'faith',
   'belief',
   'orthodoxy',
   'heresy',
   'piety',
   'reverence',
   'cathedral',
   'basilica',
   'sanctuary',
   'shrine',
   'tabernacle',
   'chapel',
   'sanctum',
   'altar',
   'sacristy',
   'choir',
   'liturgy',
   'sacrament',
   'baptism',
   'confirmation',
   'eucharist',
   'penance',
   'matrimony',
   'ordination',
   'last rites',
   'saint',
   'martyr',
   'apostle',
   'evangelist',
   'pontiff',
   'angel',
   'seraph',
   'cherub',
   'virtue',
   'grace',
   'mercy',
   'divine',
   'providence',
   'omnipotent',
   'omniscient',
   'omnipresent',
   'heaven',
   'paradise',
   'eternity',
   'salvation',
   'redemption',
   'sin',
   'repentance',
   'forgiveness',
   'resurrection',
   'ascension',
   'judgment',
   'damnation',
   'purgatory',
   'limbo',
   'sacred',
   'profane',
   'blasphemy',
   'heretic',
   'sect',
   'denomination',
   'covenant',
   'testament',
   'scripture',
   'gospel',
   'apocalypse',
   'revelation',
   'psalms',
   'parable',
   'epistle',
   'exodus',
   'genesis',
   'prophet',
   'apostle',
   'disciple',
   'martyrdom',
   'asceticism',
   'meditation',
   'contemplation',
   'enlightenment',
   'nirvana',
   'zen',
   'yoga',
   'karma',
   'dharma',
   'samsara',
   'buddha',
   'bodhisattva',
   'sangha',
   'stupa',
   'mandala',
   'mantra',
   'lama',
   'monk',
   'nun',
   'guru',
   'swami',
   'ashram',
   'tantra',
   'puja',
   'havan',
   'homa',
   'bhajan',
   'kirtan',
   'gatha',
   'mahavira',
   'jainism',
   'ahimsa',
   'upanishad',
   'vedanta',
   'hinduism',
   'brahman',
   'shiva',
   'vishnu',
   'krishna',
   'ganesha',
   'durga',
   'saraswati',
   'rama',
   'sita',
   'mahabharata',
   'ramayana',
   'bhagavad gita',
   'karma yoga',
   'bhakti yoga',
   'jnana yoga',
   'ashtanga yoga',
   'om',
   'mantra',
   'samsara',
   'moksha',
   'yogi',
   'sadhu',
   'pandit',
   'puja',
   'mandir',
   'ashram',
   'ghat',
  'kumbh mela',
   'diwali',
   'holi',
  'navaratri'
  
  ]


// Array to store sent words
let sentWords = [];

// Function to shuffle characters of a word
function shuffleWord(word) {
  return word.split('').sort(() => Math.random() - 0.5).join('');
}

// Function to select a random word that has not been sent before
function selectRandomWord() {
  if (sentWords.length === words.length) {
    // If all words have been sent, reset the sentWords array
    sentWords = [];
  }
  const availableWords = words.filter(word => !sentWords.includes(word));
  const randomIndex = Math.floor(Math.random() * availableWords.length);
  const selectedWord = availableWords[randomIndex];
  sentWords.push(selectedWord);
  return selectedWord;
}

// Endpoint for /kshitiz
app.get('/kshitiz', (req, res) => {
  // Select a random word from the array
  const randomWord = selectRandomWord();

  // Scramble the selected word
  const scrambledWord = shuffleWord(randomWord);

  // Construct the response object
  const response = {
    scrambled_word: scrambledWord, // Corrected variable name here
    correct_answer: randomWord
  };

  res.json(response);
});

// Start the server
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
